# TreeOfLifeClassifier Subsetting
The TreeOfLifeClassifier creates predictions based on embeddings for the TOL taxon labels BioCLIP was trained on.

The `get_label_data()` method can be used to see the entire list of taxon label data.

The `apply_filter()` method can be used to limit the embeddings used by passing a __filter__ (boolean list of embeddings to keep).

The `create_taxa_filter()` method can be used to create filters for taxa values within TOL. Unknown taxa values will result in an error.

In [ ]:
!pip install pybioclip --quiet

In [1]:
from bioclip.predict import TreeOfLifeClassifier
from bioclip import Rank
import pandas as pd

## Run simple prediction

In [2]:
classifier = TreeOfLifeClassifier()

In [3]:
preds = classifier.predict("Ursus-arctos.jpeg", Rank.SPECIES)
pd.DataFrame(preds)

100%|██████████| 1/1 [00:02<00:00,  2.67s/images]

,file_name,kingdom,phylum,class,order,family,genus,species_epithet,species,common_name,score
0,Ursus-arctos.jpeg,Animalia,Chordata,Mammalia,Carnivora,Ursidae,Ursus,arctos,Ursus arctos,Brown Bear,0.838258
1,Ursus-arctos.jpeg,Animalia,Chordata,Mammalia,Carnivora,Ursidae,Ursus,etruscus,Ursus etruscus,,0.119141
2,Ursus-arctos.jpeg,Animalia,Chordata,Mammalia,Carnivora,Ursidae,Ursus,abstrusus,Ursus abstrusus,,0.009745
3,Ursus-arctos.jpeg,Archaeplastida,Tracheophyta,,Rosales,Rosaceae,Rubus,lasiostylus Focke,Rubus lasiostylus Focke,,0.003995
4,Ursus-arctos.jpeg,Animalia,Chordata,Mammalia,Artiodactyla,Bovidae,Ovibos,moschatus,Ovibos moschatus,Muskox,0.001062

## Predict for specific families
Use `create_taxa_filter()` to subset the embeddings for two family values.

In [4]:
taxa_filter = classifier.create_taxa_filter(
    Rank.FAMILY,
    ['Ursidae','Felidae']
)
classifier.apply_filter(taxa_filter)
preds = classifier.predict("Ursus-arctos.jpeg", Rank.SPECIES)
pd.DataFrame(preds)

100%|██████████| 1/1 [00:00<00:00,  1.88images/s]

,file_name,kingdom,phylum,class,order,family,genus,species_epithet,species,common_name,score
0,Ursus-arctos.jpeg,Animalia,Chordata,Mammalia,Carnivora,Ursidae,Ursus,arctos,Ursus arctos,Brown Bear,0.863957
1,Ursus-arctos.jpeg,Animalia,Chordata,Mammalia,Carnivora,Ursidae,Ursus,etruscus,Ursus etruscus,,0.122792
2,Ursus-arctos.jpeg,Animalia,Chordata,Mammalia,Carnivora,Ursidae,Ursus,abstrusus,Ursus abstrusus,,0.010044
3,Ursus-arctos.jpeg,Animalia,Chordata,Mammalia,Carnivora,Ursidae,Ursus,vitabilis,Ursus vitabilis,,0.000837
4,Ursus-arctos.jpeg,Animalia,Chordata,Mammalia,Carnivora,Ursidae,Ursus,thibetanus,Ursus thibetanus,Asiatic black bear,0.000754

## Display TOL label data

In [5]:
label_data = classifier.get_label_data()
label_data

,kingdom,phylum,class,order,family,genus,species_epithet,species,common_name
0,Animalia,,,,,Acanthodes,pristis,Acanthodes pristis,
1,Animalia,,,,,Afghanobuthus,naumanni,Afghanobuthus naumanni,
2,Animalia,,,,,Afghanorthochirus,danielleae,Afghanorthochirus danielleae,
3,Animalia,,,,,Afghanorthochirus,erardi,Afghanorthochirus erardi,
4,Animalia,,,,,Afghanorthochirus,monodi,Afghanorthochirus monodi,
...,...,...,...,...,...,...,...,...,...
867450,Viruses,Pisuviricota,Stelpaviricetes,Patatavirales,Potyviridae,Potyvirus,Watermelon mosaic virus,Potyvirus Watermelon mosaic virus,
867451,Viruses,Pisuviricota,Stelpaviricetes,Patatavirales,Potyviridae,Potyvirus,Wisteria vein mosaic virus,Potyvirus Wisteria vein mosaic virus,
867452,Viruses,Uroviricota,Caudoviricetes,Caudovirales,Myoviridae,Klausavirus,colucci,Klausavirus colucci,
867453,Viruses,Uroviricota,Caudoviricetes,Caudovirales,Myoviridae,Klausavirus,princesstrina,Klausavirus princesstrina,
867454,Viruses,Uroviricota,Caudoviricetes,Caudovirales,Siphoviridae,Decurrovirus,decurro,Decurrovirus decurro,

## Create custom filter
Demonstrates creating a custom filter by removing two species

In [6]:
label_data = classifier.get_label_data()
taxa_filter = ~label_data.species.isin(["Ursus arctos", "Ursus arctos syriacus"])

In [7]:
classifier.apply_filter(taxa_filter)
preds = classifier.predict("Ursus-arctos.jpeg", Rank.SPECIES)
pd.DataFrame(preds)

100%|██████████| 1/1 [00:02<00:00,  2.70s/images]

,file_name,kingdom,phylum,class,order,family,genus,species_epithet,species,common_name,score
0,Ursus-arctos.jpeg,Animalia,Chordata,Mammalia,Carnivora,Ursidae,Ursus,etruscus,Ursus etruscus,,0.735816
1,Ursus-arctos.jpeg,Animalia,Chordata,Mammalia,Carnivora,Ursidae,Ursus,abstrusus,Ursus abstrusus,,0.060188
2,Ursus-arctos.jpeg,Archaeplastida,Tracheophyta,,Rosales,Rosaceae,Rubus,lasiostylus Focke,Rubus lasiostylus Focke,,0.024674
3,Ursus-arctos.jpeg,Animalia,Chordata,Mammalia,Artiodactyla,Bovidae,Ovibos,moschatus,Ovibos moschatus,Muskox,0.006557
4,Ursus-arctos.jpeg,Animalia,Chordata,Mammalia,Primates,Hominidae,Homo,floresiensis,Homo floresiensis,Hobbit,0.005990